### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ky0225** [ky0225/furima-36207#23]
# URL
https://furima-36207.herokuapp.com/

# Basic認証
ID: admin
Pass: 2222

# 出品者用のメールアドレスとパスワード
メールアドレス：sell@test
Pass：test0225

# 購入者用のメールアドレスとパスワード
メールアドレス：buy@test
Pass：test0225

**Comment by takumi0530** [comment]
@ky0225 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/127271687-374bb07e-ee72-4c02-9198-518cbaddef8f.png)

### **【補足】※達成要件に関係ありません。**
出品・編集ページのビューに一部崩れがありました。修正しても報告は結構ですので、引き続き頑張って下さい！
<img width="1435" alt="スクリーンショット 2021-07-28 15 02 24" src="https://user-images.githubusercontent.com/76197191/127271783-e247d978-00f4-4d8f-a5d6-8d58f63ed64c.png">
